openapi: 3.0.0
info:
  title: PCF Platform S2S API
  version: 1.0.0
  description: Service to Service API of the PCF Platform


servers:
  - url: https://{customerId}.{projectType}
    variables:
      customerId:
        default: dev
        description: Customer name
      projectType:
        default: hostname
        description: Hostname
  - url:  http://127.0.0.1:{port}
    variables:
      port:
        default: "80"
        description: Port to reach the backend



tags:
- name: "Retrieve Token"  
  description: "Uset to retrieve the Access-token"
- name: "Data Upload"
  description: "Enables the upload of data and triggering the calculation "
- name: "Result Export"
  description: "S2S API Result Export"
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Requires a valid Bearer token in the Authorization header.  Example:          Authorization: Bearer eyJhbGc..."
  schemas:  
    Results:   
      type: object
      properties:
        scenario_id:
          type: string
          description: Id of the scenario.
        numTotalEntries:
          type: float
          description: Number of entries. 
        data:
          type: array
          description: Array of data entries
          items:
            type: object
            properties:
              reviewStatus:
                type: string 
              odId:
                type: string 
              odText:
                type: string 
              buId:
                type: string 
              region:
                type: string 
              companyId:
                type: string 
              companyText:
                type: string 
              pbgId:
                type: string 
              pbgText:
                type: string 
              prodLevel1:
                type: string 
              prodLevel1Text:
                type: string 
              prodLevel2:
                type: string 
              prodLevel2Text:
                type: string 
              prodLevel3:
                type: string 
              prodLevel3Text:
                type: string 
              orgAttr1:
                type: string 
              orgAttr1Text:
                type: string 
              orgAttr2:
                type: string 
              orgAttr2Text:
                type: string 
              businessProcessId: 
                type: string 
              businessProcessText: 
                type: string 
              scope1: 
                type: number 
              scope2: 
                type: number
              scope3: 
                type: number
              sumScope123: 
                type: number
              biogenicPCF: 
                type: number
              RSPOsavings: 
                type: number
              PCFinclBiogenic:
                type: number
              sumAllPCF: 
                type: number
              volume: 
                type: number
              areaKey:
                type: string 
        rawMaterials:
          type: array
          description: Array of data entries
          items:
            type: object
            properties:
              start_pbg:
                type: string 
              productId:
                type: string 
              productDescription:
                type: string 
              companyId:
                type: string 
              companyDescription: 
                type: string 
              totalInputFactor:
                type: number
              scope3Emission:
                type: integer
              emissionContribution:
                type: number
              quantity: 
                type: integer
              onstageScope3Rawm: 
                type: integer
              contributionScope3Rawm: 
                type: number
              onstageScope3Transport: 
                type: number
              contributionScope3Transport: 
                type: number
              isResidue: 
                type: boolean
              totalPCF: 
                type: number
              sumScope3: 
                type: number
              sumScope3Rawm: 
                type: number
              sumScope3Transport: 
                type: number
              percentageEmissionContribution: 
                type: number
              percentageTotalEmissionContribution:
                type: number
              datasetRegion:
                type: string 
              datasetName: 
                type: string
              datasetGUID: 
                type: string
              datasetSource: 
                type: string
              datasetCas: 
                type: string
              flagQualityProduct: 
                type: number
              flagQualityRegion: 
                type: number
              carbonContentTotal:
                type: number
              carbonContentBiogenic:
                type: number
       
paths:
  /s2sapi/v1/auth/token:
    post:
      tags:
      - "Retrieve Token"      
      summary: Returns Access token
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:          # <!--- form field name
                  type: string
                  description:  client_credentials
                client_id:    # <!--- form field name
                  type: string
                  description: s2s-api
                client_secret:    # <!--- form field name
                  description: Secret provided by Eviden
                  type: string

      responses:
        '200':
          description: Access token retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: The access token issued by the authorization server.
                  token_type:
                    type: string
                    description: The type of the token issued.
                  expires_in:
                    type: integer
                    format: int32
                    description: The lifetime in seconds of the access token.
                  scope:
                    type: string
                    description: Scope of the access token.

  /s2sapi/v1/file/uploadurls:
    post:
      security:
      - bearerAuth: []      
      tags:
      - "Data Upload"
      summary: Returns Signed Upload URLS for the 
      description: Provides Signed Upload URLS (GCS) used to upload data into the Cloud Storage
      parameters:
        - name: data_type
          in: query
          required: true
          schema:
            type: string
            enum:
              - xlsm
              - csv
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bucket_name:
                    type: string
                  folder_name:
                    type: string
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        file_name:
                          type: string
                        signed_url:
                          type: string

  /s2sapi/v1/scenario:
    post:
      security:
      - bearerAuth: []      
      tags:
      - "Data Upload"
      summary: Create a new scenario
      description: Once the data are available within the GCP this function is used to trigger the scenario creation as well as the calculation of it.
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: base_scenario
          in: query
          required: false
          schema:
            type: string   
        - name: comment
          in: query
          required: false
          schema:
            type: string   
        - name: main
          in: query
          required: true
          schema:
            type: boolean   
        - name: bucket_name
          in: query
          required: true
          schema:
            type: string   
        - name: folder_name
          in: query
          required: true
          schema:
            type: string       
      responses:
        '200':
          description: Successful creation of a scenario
          content:
            application/json:
              schema:
                type: object
                properties:
                  scenario_id:
                    type: string
                  name:
                    type: string
                  scheme_name:
                    type: string
                  base_scenario:
                    type: string
                    nullable: true
                  base_scenario_name:
                    type: string
                  status:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                  comment:
                    type: string
                    nullable: true
                  created_by:
                    type: string
                  created_by_name:
                    type: string
                  modifiable:
                    type: boolean
                  deletable:
                    type: boolean
                  default_scenario:
                    type: string
                    nullable: true
                  deleted:
                    type: boolean
    get:
      security:
      - bearerAuth: []
      tags:
      - "Data Upload"
      summary: Get scenario status 
      description:  Retruns the status of the selected scenarion or all scenarios. Requires either 'scenario_id' or 'scenario_name' as a query parameter.
      parameters:
        - name: scenario_id
          in: query
          required: false
          schema:
            type: string
        - name: scenario_name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of scenarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    scenario_id:
                      type: string
                    name:
                      type: string
                    scheme_name:
                      type: string
                    base_scenario:
                      type: string
                    base_scenario_name:
                      type: string
                    status:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                    comment:
                      type: string
                    created_by:
                      type: string
                    created_by_name:
                      type: string
                    modifiable:
                      type: boolean
                    deletable:
                      type: boolean
                    default_scenario:
                      type: string
                      nullable: true
                    deleted:
                      type: boolean
    delete:
      tags:
      - "Data Upload"
      security:
      - bearerAuth: []
      summary: Delete a scenario
      description: Used to delete a specific scenario      
      parameters:
        - name: scenario_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Scenario deleted
    put:
      security:
      - bearerAuth: []
      tags:
      - "Data Upload"
      summary: Update scenario and calculate
      description: Used to update a specific scenario (e.g uploaded data has changed), also the calculation is triggered.  Requires either 'scenario_id' or 'scenario_name' as a query parameter.
      parameters:
        - name: scenario_id
          in: query
          schema:
            type: string
        - name: scenario_name
          in: query:
          schema:
            type: string
        - name: bucket_name
          in: query
          required: true
          schema:
            type: string
        - name: folder_name
          in: query
          required: false
          schema:
            type: string
        - name: run_calc
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Scenario updated

  /s2sapi/v1/scenario/calculate:
    post:
      security:
      - bearerAuth: []
      tags:
      - "Data Upload"
      summary: Trigger a scenario calculation
      description: Used to manually trigger a re-calculation of a scenario.  Requires either 'scenario_id' or 'scenario_name' as a query parameter.  Requires either 'scenario_id' or 'scenario_name' as a query parameter.
      parameters:
        - name: scenario_id
          in: query
          schema:
            type: string
        - name: scenario_name
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Calculation triggered
          
  /s2sapi/v1/scenario/results/{scenarioId}:
    get:
      security:
      - bearerAuth: []
      tags:
      - "Result Export"
      summary: Trigger a scenario result download
      description: Used to dowload scenario calculation results, if no scenarioId will be provided the default scenario will be provided
      parameters:
        - name: scenarioId
          in: path
          required: true
          description: allowed to be empty
          schema:
            type: string
        - name: includeRawMaterials
          in: query
          required: false
          description: allowed to be empty
          schema:
            type: boolean            
            enum: [true,false]
      responses:
        '200':
          description: Calculation triggered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
/s2sapi/v1/scenario/results_by_name/{scenarioName}:
    get:
      security:
      - bearerAuth: []
      tags:
      - "Result Export"
      summary: Trigger a scenario result download
      description: Used to dowload scenario calculation results, if no scenarioId will be provided the default scenario will be provided
      parameters:
        - name: scenarioName
          in: path
          required: true
          description: allowed to be empty
          schema:
            type: string
        - name: includeRawMaterials
          in: query
          required: false
          description: allowed to be empty
          schema:
            type: boolean            
            enum: [true,false]
      responses:
        '200':
          description: Calculation triggered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'