name: Release Workflow

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
      

jobs:
  # This reusable action is used to retrieve to which branch the given tag belongs to, otherwise we later cannot retrieve the full commit history
  build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
    - name: Add header
      run: |
        echo "" > ../release_notes.txt  
    - id: release-note
      uses: DE-NZT-TRACS/tracs-githubaction-releasenote@v5
      with:
        repo-name: DE-NZT-TRACS/tracs-s2s-api
        branch-name: "main"
        jira-token: ${{ secrets.JIRA_API_TOKEN }}
        jira-url: "https://jira.fsc.atos-services.net"
        github-token: ${{ secrets.ACTIONS_TOKEN }}
        file-destination: .  
    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        #tag: ${{ github.ref }}
        #name: Release ${{ github.ref }}
        bodyFile: ../release_notes.txt
        #body: ${{ steps.set-release-notes.outputs.RELEASE_NOTES }}
